/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafxdemo;

import java.io.File;
import java.net.URL;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.stage.FileChooser;

import javafx.event.ActionEvent;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;

public class App extends Application{
    
    //控件素材图片
    public static String playIcon  = "/icon/play.png";
    public static String pauseIcon  = "/icon/pause.png";
    public static String stopIcon  = "/icon/stop.png";
    public static String volOffIcon  = "/icon/volume_off.png";
    public static String volOnIcon  = "/icon/volume_on.png";
    public static String maxIcon  = "/icon/max.png";
    public static String openIcon  = "/icon/open.png";
    public static URL xmlUrl = App.class.getResource("/player.fxml");
    public static String videoPath = "";

    final FileChooser fileChooser = new FileChooser();

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        launch();
    }
    @Override
    public void start(Stage primaryStage) throws Exception{

        /*File file = fileChooser.showOpenDialog(primaryStage);
        if (file == null) {
            return;
        }
        App.videoPath = file.getAbsolutePath();*/
        SimpleMediaPlayer.popup(App.videoPath,800,600);
        return;
        /*
        //创建测试窗口
        primaryStage.setTitle("视频播放器1.0");
        Group root = new Group();
        BorderPane pane = new BorderPane();

        root.getChildren().add(pane);
        HBox hbox = new HBox();
        hbox.setAlignment(Pos.CENTER);
        pane.setBottom(hbox);
        Button popup = new Button("Popup");
        Button popup2 = new Button("Popup small");
        hbox.getChildren().addAll(popup,popup2);
        
        System.out.println(App.videoPath);

        //测试嵌入式调用
        SimpleMediaPlayer player = SimpleMediaPlayer.newInstance(App.videoPath);
        pane.setCenter(player);
        pane.setAlignment(player,Pos.CENTER);

        //测试弹窗式调用
        popup.setOnAction((ActionEvent e)->{
            SimpleMediaPlayer.popup(App.videoPath);
        });
        popup2.setOnAction((ActionEvent e)->{
            SimpleMediaPlayer.popup(App.videoPath,550,400);
        });

        primaryStage.setScene(new Scene(root, 600, 500));
        primaryStage.show();*/
    }
    /*@Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");

        //定义btn1
        Button btn1 = new Button("Button01");
        btn1.setPrefSize(100, 30);

        //设置间隔
        AnchorPane.setTopAnchor(btn1, 50.0);
        AnchorPane.setLeftAnchor(btn1, 50.0);

        //定义btn2
        Button btn2 = new Button("Button02");
        btn2.setPrefSize(100, 30);
        //设置间隔
        AnchorPane.setBottomAnchor(btn2, 50.0);
        AnchorPane.setRightAnchor(btn2, 50.0);

        //定义AnchorPane,添加node
        AnchorPane anchorPane = new AnchorPane();
        anchorPane.getChildren().addAll(btn1, btn2, l);

        Scene scene = new Scene(anchorPane, 640, 480);//new StackPane(l), 640, 480);
        stage.setScene(scene);
        stage.show();
    }*/
}
